Added css button
Design-and-Code/css-buttons pull request #145
Opened 2022-10-28 08:35 UTC by Abhishek-dab

> **Note**
> - We strictly follow the Contribution Guideline and expect contributors to follow it as well. 
> - If a lot of conflicts/changes are requested in the PR, please open a new PR with the requested changes (either you or we can close the PR). 

## Have you read the Contribution Guidelines? If not, check [CONTRIBUTING.md](https://github.com/Design-and-Code/css-buttons/blob/main/CONTRIBUTING.md) file first.

Yes

## Description

Added a new CSS button

## Class Naming Convention for your button
- [x] Does your html `button` element have class-name like this: `your_github_username-button-index` (example: `rajkumar-justcoder-button-1` ). 

## Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

> mark `[X]` to make it checked.

## Related Issues

Fixes Issue #144 (write number after `#`)

## Screenshot
![image](https://user-images.githubusercontent.com/67536261/198543030-22d736aa-24f1-46a3-9a51-ff9ad83ee488.png)

2022-10-31 16:29 UTC, Abhishek-dab commented
Hi @Rajkumar-justcoder , can you pls check the PR and merge it.
Thanks.

2022-11-01 15:54 UTC, Rajkumar-justcoder requested changes

2022-11-01 15:54 UTC, Rajkumar-justcoder commented on buttons/buttons.css
> +    background-color: initial;
pls change your classes names to as i said it should be your github-username not name so githubusername-btn-1

2022-11-01 15:55 UTC, Rajkumar-justcoder commented on buttons/buttons.css
> +    background-color: initial;
also pls be creative this is just simple change

2022-11-09 04:31 UTC, closed without merging